// Fallback offline do autocomplete de cidade: usado só quando a API do IBGE
// não responde. Cobre as 27 capitais e os principais polos industriais/CDs
// do país — suficiente para o campo nunca ficar sem sugestões.

export const CITIES_FALLBACK: ReadonlyArray<{ name: string; uf: string }> = [
  // Capitais
  { name: "Rio Branco", uf: "AC" },
  { name: "Maceió", uf: "AL" },
  { name: "Macapá", uf: "AP" },
  { name: "Manaus", uf: "AM" },
  { name: "Salvador", uf: "BA" },
  { name: "Fortaleza", uf: "CE" },
  { name: "Brasília", uf: "DF" },
  { name: "Vitória", uf: "ES" },
  { name: "Goiânia", uf: "GO" },
  { name: "São Luís", uf: "MA" },
  { name: "Cuiabá", uf: "MT" },
  { name: "Campo Grande", uf: "MS" },
  { name: "Belo Horizonte", uf: "MG" },
  { name: "Belém", uf: "PA" },
  { name: "João Pessoa", uf: "PB" },
  { name: "Curitiba", uf: "PR" },
  { name: "Recife", uf: "PE" },
  { name: "Teresina", uf: "PI" },
  { name: "Rio de Janeiro", uf: "RJ" },
  { name: "Natal", uf: "RN" },
  { name: "Porto Alegre", uf: "RS" },
  { name: "Porto Velho", uf: "RO" },
  { name: "Boa Vista", uf: "RR" },
  { name: "Florianópolis", uf: "SC" },
  { name: "São Paulo", uf: "SP" },
  { name: "Aracaju", uf: "SE" },
  { name: "Palmas", uf: "TO" },

  // Polos industriais / logísticos relevantes
  { name: "Guarulhos", uf: "SP" },
  { name: "Campinas", uf: "SP" },
  { name: "São Bernardo do Campo", uf: "SP" },
  { name: "Santo André", uf: "SP" },
  { name: "Osasco", uf: "SP" },
  { name: "Sorocaba", uf: "SP" },
  { name: "Ribeirão Preto", uf: "SP" },
  { name: "São José dos Campos", uf: "SP" },
  { name: "Jundiaí", uf: "SP" },
  { name: "Santos", uf: "SP" },
  { name: "Piracicaba", uf: "SP" },
  { name: "Cajamar", uf: "SP" },
  { name: "Barueri", uf: "SP" },
  { name: "Louveira", uf: "SP" },
  { name: "Extrema", uf: "MG" },
  { name: "Betim", uf: "MG" },
  { name: "Contagem", uf: "MG" },
  { name: "Uberlândia", uf: "MG" },
  { name: "Juiz de Fora", uf: "MG" },
  { name: "Duque de Caxias", uf: "RJ" },
  { name: "Nova Iguaçu", uf: "RJ" },
  { name: "Campos dos Goytacazes", uf: "RJ" },
  { name: "Serra", uf: "ES" },
  { name: "Vila Velha", uf: "ES" },
  { name: "Cariacica", uf: "ES" },
  { name: "Joinville", uf: "SC" },
  { name: "Blumenau", uf: "SC" },
  { name: "Itajaí", uf: "SC" },
  { name: "Chapecó", uf: "SC" },
  { name: "Caxias do Sul", uf: "RS" },
  { name: "Canoas", uf: "RS" },
  { name: "Gravataí", uf: "RS" },
  { name: "Novo Hamburgo", uf: "RS" },
  { name: "Londrina", uf: "PR" },
  { name: "Maringá", uf: "PR" },
  { name: "Ponta Grossa", uf: "PR" },
  { name: "São José dos Pinhais", uf: "PR" },
  { name: "Cascavel", uf: "PR" },
  { name: "Anápolis", uf: "GO" },
  { name: "Aparecida de Goiânia", uf: "GO" },
  { name: "Feira de Santana", uf: "BA" },
  { name: "Camaçari", uf: "BA" },
  { name: "Jaboatão dos Guararapes", uf: "PE" },
  { name: "Caruaru", uf: "PE" },
  { name: "Suape", uf: "PE" },
  { name: "Simões Filho", uf: "BA" },
];
